name: bagel
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - torchvision
  - cudnn
  - numpy
  - opencv
  - libglib          # provides libgthread-2.0
  - pip:
      - flash-attn==2.8.3
      - -r requirements.txt
